language: scala
scala:
  - 2.10.5
  - 2.11.7
jdk: oraclejdk7
env:
  global:
  - secure: IgzqZjDGDiXkBrGoTdAdj/em5C+rO48QSdeA3K0FTzuti8VuC4U7RslqiqokF1QziOxA6GYjB0sfVdupAnDmyuYLUjDDvvEuQu73bt1fucQxho2xUHq678xjorV2xKrAKriiFG8i4HMFNVL+vKKtScGTkjyNI29bdLYJS7Bftgw=
rvm:
  - "1.9.3-p392"
script: bash bin/travis
webhooks:
  urls:
    - https://webhooks.gitter.im/e/aadbcad1ca1e91b5a189
  on_success: change
  on_failure: always
  on_start: false
